import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { businessQueryKey } from "../../app/query-client";
import { Button, DetailGrid, EmptyState, Field, Modal, PageHeader, Pagination, SelectField, Spinner, StatusBadge, TextAreaField, useToast } from "../../components/ui";
import { errorMessage } from "../../lib/api/client";
import { fulfillmentsApi } from "../../lib/api/resources";
import type { Fulfillment } from "../../lib/api/types";
import { useBusiness } from "../businesses/business-context";

const statuses = ["", "pending", "submitting", "submitted", "in_progress", "completed", "partial", "cancelled", "failed", "submission_unknown"];
export function FulfillmentsPage() {
  const business = useBusiness(); const client = useQueryClient(); const toast = useToast();
  const [offset, setOffset] = useState(0); const [status, setStatus] = useState(""); const [detail, setDetail] = useState<Fulfillment | null>(null); const [dispatching, setDispatching] = useState(false); const [formError, setFormError] = useState("");
  const query = useQuery({ queryKey: businessQueryKey("fulfillments", business.id, { offset, status }), queryFn: () => fulfillmentsApi.list(business.id, { limit: 25, offset, status }) });
  const refresh = async () => client.invalidateQueries({ queryKey: ["fulfillments", business.id] });
  const dispatch = useMutation({ mutationFn: ({ orderId, orderItemId, input }: { orderId: string; orderItemId: string; input: Record<string, unknown> }) => fulfillmentsApi.dispatch(business.id, orderId, { orderItemId, input }), onSuccess: async () => { setDispatching(false); await refresh(); toast("Fulfillment enviado al Core."); } });
  const action = useMutation({ mutationFn: ({ id, mode }: { id: string; mode: "retry" | "sync" }) => mode === "retry" ? fulfillmentsApi.retry(business.id, id) : fulfillmentsApi.sync(business.id, id), onSuccess: async (updated) => { setDetail(updated); await refresh(); toast("Fulfillment actualizado."); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFormError(""); const data = new FormData(event.currentTarget); try { const parsed = JSON.parse(String(data.get("input"))) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); dispatch.mutate({ orderId: String(data.get("orderId")), orderItemId: String(data.get("orderItemId")), input: parsed as Record<string, unknown> }); } catch { setFormError("El input debe ser un objeto JSON válido y sin secretos."); } }
  return <><PageHeader title="Fulfillments" description="Operación conservadora: submission_unknown nunca ofrece reintento." action={<Button onClick={() => setDispatching(true)}>Dispatch</Button>} /><div className="filter-bar"><SelectField label="Estado" value={status} onChange={(event) => { setStatus(event.target.value); setOffset(0); }}>{statuses.map((value) => <option key={value} value={value}>{value || "Todos"}</option>)}</SelectField></div>
    {query.isLoading ? <Spinner /> : query.isError ? <div className="alert error">{errorMessage(query.error)}</div> : !query.data?.length ? <EmptyState title="No hay fulfillments." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Order</th><th>Proveedor</th><th>Servicio</th><th>Cantidad</th><th>Estado</th><th /></tr></thead><tbody>{query.data.map((item) => <tr key={item.id}><td><code>{item.id.slice(0, 8)}</code></td><td><code>{item.orderId.slice(0, 8)}</code></td><td>{item.providerKey}</td><td>{item.externalServiceId}</td><td>{item.quantity}</td><td><StatusBadge value={item.status} /></td><td><Button className="secondary small" onClick={() => setDetail(item)}>Ver</Button></td></tr>)}</tbody></table></div><Pagination offset={offset} limit={25} count={query.data.length} onChange={setOffset} /></div>}
    {detail && <Modal title="Detalle de fulfillment" onClose={() => setDetail(null)}><DetailGrid record={detail as unknown as Record<string, unknown>} /><div className="form-actions">{detail.providerOrderId && <Button className="secondary" disabled={action.isPending} onClick={() => action.mutate({ id: detail.id, mode: "sync" })}>Sincronizar estado</Button>}{business.role !== "operator" && detail.status === "failed" && <Button className="danger" disabled={action.isPending} onClick={() => { if (window.confirm("¿Reintentar este fulfillment fallido?")) action.mutate({ id: detail.id, mode: "retry" }); }}>Reintentar</Button>}</div>{action.isError && <div className="alert error">{errorMessage(action.error)}</div>}</Modal>}
    {dispatching && <Modal title="Despachar fulfillment" onClose={() => setDispatching(false)}><form onSubmit={submit}><Field label="Order ID" name="orderId" required /><Field label="Order item ID" name="orderItemId" required /><TextAreaField label="Input JSON permitido por el proveedor" name="input" defaultValue={'{"link":"https://..."}'} required /><p className="muted">No incluyas API keys, tokens ni campos reservados. El backend valida el payload.</p>{(formError || dispatch.isError) && <div className="alert error">{formError || errorMessage(dispatch.error)}</div>}<div className="form-actions"><Button className="secondary" type="button" onClick={() => setDispatching(false)}>Cancelar</Button><Button type="submit" disabled={dispatch.isPending}>Despachar</Button></div></form></Modal>}
  </>;
}
